

services:
  # mongo:
  #   image: mongo:6
  #   container_name: besta-mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  # redis:
  #   image: redis:7
  #   container_name: besta-redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

  mysql:
    image: mysql:8
    container_name: besta-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: besta
      MYSQL_USER: bestauser
      MYSQL_PASSWORD: bestapass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "bestauser", "-pbestapass"]
      interval: 5s
      timeout: 5s
      retries: 20


  backend:
    build:
      context: ./backend
    container_name: besta-backend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: node app.js
    environment:
      DATABASE_URL: mysql://bestauser:bestapass@mysql:3306/besta
    depends_on:
      mysql:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-development
    container_name: besta-frontend
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  # mongo_data:
  redis_data:
  mysql_data:
  frontend_node_modules:
